create sequence hibernate_sequence start 1 increment 1;
create table athlete (id int8 not null, country int8, name varchar(255), primary key (id));
create table country (id int8 not null, name varchar(255), primary key (id));
create table race (id int8 not null, country int8, distance varchar(255), height_gain varchar(255), name varchar(255), primary key (id));
create table ranking (id int8 not null, athlete int8, position int4, race int8, primary key (id));
alter table athlete add constraint FKqjykv33ptrcbovbabjfkevmw0 foreign key (country) references country;
alter table race add constraint FKtdv6b31vt49eoaofpbdawj8mt foreign key (country) references country;
alter table ranking add constraint FKt0n68oif19i9tr8joxm6oou8b foreign key (athlete) references athlete;
alter table ranking add constraint FKk6soicjavkjevn7p5uos775x9 foreign key (race) references race;
create sequence hibernate_sequence start 1 increment 1;
create table athlete (id int8 not null, country int8 not null, name varchar(255), primary key (id));
create table country (id int8 not null, name varchar(255), primary key (id));
create table race (id int8 not null, country int8, distance varchar(255), height_gain varchar(255), name varchar(255), primary key (id));
create table ranking (id int8 not null, athlete int8, position int4, race int8, primary key (id));
alter table athlete add constraint FKqjykv33ptrcbovbabjfkevmw0 foreign key (country) references country;
alter table race add constraint FKtdv6b31vt49eoaofpbdawj8mt foreign key (country) references country;
alter table ranking add constraint FKt0n68oif19i9tr8joxm6oou8b foreign key (athlete) references athlete;
alter table ranking add constraint FKk6soicjavkjevn7p5uos775x9 foreign key (race) references race;
create sequence hibernate_sequence start 1 increment 1;
create table athlete (id int8 not null, country int8 not null, name varchar(255), primary key (id));
create table country (id int8 not null, name varchar(255), primary key (id));
create table race (id int8 not null, country int8, distance varchar(255), height_gain varchar(255), name varchar(255), primary key (id));
create table ranking (id int8 not null, athlete int8, position int4, race int8, primary key (id));
alter table athlete add constraint FKqjykv33ptrcbovbabjfkevmw0 foreign key (country) references country;
alter table race add constraint FKtdv6b31vt49eoaofpbdawj8mt foreign key (country) references country;
alter table ranking add constraint FKt0n68oif19i9tr8joxm6oou8b foreign key (athlete) references athlete;
alter table ranking add constraint FKk6soicjavkjevn7p5uos775x9 foreign key (race) references race;
create sequence hibernate_sequence start 1 increment 1;
create table athlete (id int8 not null, country int8 not null, name varchar(255), primary key (id));
create table country (id int8 not null, name varchar(255), primary key (id));
create table race (id int8 not null, country int8, distance varchar(255), height_gain varchar(255), name varchar(255), primary key (id));
create table ranking (id int8 not null, athlete int8, position int4, race int8, primary key (id));
alter table athlete add constraint FKqjykv33ptrcbovbabjfkevmw0 foreign key (country) references country;
alter table race add constraint FKtdv6b31vt49eoaofpbdawj8mt foreign key (country) references country;
alter table ranking add constraint FKt0n68oif19i9tr8joxm6oou8b foreign key (athlete) references athlete;
alter table ranking add constraint FKk6soicjavkjevn7p5uos775x9 foreign key (race) references race;
create sequence hibernate_sequence start 1 increment 1;
create table athlete (id int8 not null, country int8 not null, name varchar(255), primary key (id));
create table country (id int8 not null, name varchar(255), primary key (id));
create table race (id int8 not null, country int8, distance varchar(255), height_gain varchar(255), name varchar(255), primary key (id));
create table ranking (id int8 not null, athlete int8, position int4, race int8, primary key (id));
alter table athlete add constraint FKqjykv33ptrcbovbabjfkevmw0 foreign key (country) references country;
alter table race add constraint FKtdv6b31vt49eoaofpbdawj8mt foreign key (country) references country;
alter table ranking add constraint FKt0n68oif19i9tr8joxm6oou8b foreign key (athlete) references athlete;
alter table ranking add constraint FKk6soicjavkjevn7p5uos775x9 foreign key (race) references race;
create sequence hibernate_sequence start 1 increment 1;
create table athlete (id int8 not null, country int8 not null, name varchar(255), primary key (id));
create table country (id int8 not null, name varchar(255), primary key (id));
create table race (id int8 not null, country int8, distance varchar(255), height_gain varchar(255), name varchar(255), primary key (id));
create table ranking (id int8 not null, athlete int8, position int4, race int8, primary key (id));
alter table athlete add constraint FKqjykv33ptrcbovbabjfkevmw0 foreign key (country) references country;
alter table race add constraint FKtdv6b31vt49eoaofpbdawj8mt foreign key (country) references country;
alter table ranking add constraint FKt0n68oif19i9tr8joxm6oou8b foreign key (athlete) references athlete;
alter table ranking add constraint FKk6soicjavkjevn7p5uos775x9 foreign key (race) references race;
