spring:
   profiles:
      active: development
   application:
      name: Demo-Docker
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/demodocker
      username: demo
      password: demo
   jpa:
      properties:
         hibernate:
            show-sql: true
            dialect: org.hibernate.dialect.PostgreSQLDialect
            hbm2ddl:
               delimiter: ";" 
         javax:
            persistence:
               schema-generation:
                  create-source: metadata
                  scripts:
                     action: create
                     create-target: create.sql